name: update readme:w
on:
  schedule:
    - cron: "0 3 * * *" # 午前0時に実行(UTC基準なので9時間引く)
  workflow_dispatch:
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: run python
        run: |
          python uranai.py
          python update_readme.py
      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git add output.txt
          git commit -m "update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
